# -*- coding: utf-8 -*-
"""Intelligent_Resume_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYsUZxQvKpT6ITOZbMBYF_l7l1GuLbIb
"""

import re
import json
from datetime import datetime


class ResumeAnalyzer:

    def __init__(self):

        self.required_skills = [
            "Python",
            "SQL",
            "Machine Learning",
            "Pandas",
            "Data Analysis"
        ]

        self.minimum_experience = 2

    # Extract Name
    def extract_name(self, text):

        pattern = r"Name[:\- ]+(.*)"

        match = re.search(pattern, text, re.IGNORECASE)

        if match:
            return match.group(1).strip()

        return "Not Found"

    # Extract Email
    def extract_email(self, text):

        pattern = r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"

        match = re.search(pattern, text)

        if match:
            return match.group()

        return "Not Found"

    # Extract Skills
    def extract_skills(self, text):

        found_skills = []

        for skill in self.required_skills:

            if skill.lower() in text.lower():
                found_skills.append(skill)

        return found_skills

    # Extract Experience
    def extract_experience(self, text):

        pattern = r"(\d+)\s+years"

        match = re.search(pattern, text, re.IGNORECASE)

        if match:
            return int(match.group(1))

        return 0

    # Calculate Match Score
    def calculate_score(self, skills, experience):

        matched_skills = []

        for skill in self.required_skills:

            if skill in skills:
                matched_skills.append(skill)

        skill_score = (
            len(matched_skills) /
            len(self.required_skills)
        ) * 100

        if experience >= self.minimum_experience:
            experience_score = 100
        else:
            experience_score = (
                experience /
                self.minimum_experience
            ) * 100

        final_score = (
            (skill_score * 0.7) +
            (experience_score * 0.3)
        )

        return round(final_score, 2), matched_skills

    # Recommendation
    def recommendation(self, score):

        if score >= 80:
            return "Strong Hire"

        if score >= 60:
            return "Consider"

        return "Reject"

    # Generate Full Report
    def analyze_resume(self, resume_text):

        name = self.extract_name(resume_text)

        email = self.extract_email(resume_text)

        skills = self.extract_skills(resume_text)

        experience = self.extract_experience(resume_text)

        score, matched_skills = (
            self.calculate_score(
                skills,
                experience
            )
        )

        report = {
            "candidate_name": name,
            "email": email,
            "skills_found": skills,
            "matched_skills": matched_skills,
            "experience": experience,
            "match_score": score,
            "recommendation": self.recommendation(score),
            "generated_at": str(datetime.now())
        }

        return report


# Sample Resume
resume_text = """

Name: Rameka Sen

Email: ramekasen@gmail.com

Skills:
Python, SQL, Machine Learning,
Pandas, Data Analysis

Experience:
3 years as Data Analyst

"""

# Analyze Resume
analyzer = ResumeAnalyzer()

report = analyzer.analyze_resume(resume_text)

# Print Report
print("\n===== RESUME ANALYSIS =====\n")

for key, value in report.items():
    print(f"{key}: {value}")

# Save JSON Report
with open("report.json", "w") as json_file:

    json.dump(report, json_file, indent=4)

print("\nReport saved successfully!")

